name: Arclands
description: The Unofficial Info App! Arclands is a game about creating a buzzing village and becoming a powerful enough wizard to defend it. Build a settlement, keep your citizens happy and explore the treacherous wilds in this RPG-lite city builder.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  asset_cache: ^0.2.3
  url_launcher: ^5.7.10
  bordered_text: ^1.0.1
  cupertino_icons: ^1.0.0
  particles_flutter: ^0.1.2
  flare_splash_screen: ^3.0.1
  font_awesome_flutter: ^8.10.0
  # assets_audio_player: ^2.0.13+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: luncher_icon
  ios: false
  image_path: assets/images/icon_512.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - assets/animations/Arclands.flr
  #  - assets/fonts/

  fonts:
    - family: Grange
      fonts:
        - asset: assets/fonts/Grange.ttf
  #      - asset: assets/fonts/Grange-Shadow.ttf
  #        style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700